apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-be-multi-ride
  namespace: multi-ride-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-multi-ride
  template:
    metadata:
      labels:
        app: app-multi-ride
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: bend-multi-ride
          image: naveensasalu/multi-ride-backend:1.0.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 5000
          env:
            - name: GOOGLE_MAPS_API_KEY # This is the name your Node.js code looks for
              valueFrom:
                secretKeyRef:
                  name: maps-secrets # The name of the K8s Secret
                  key: GOOGLE_API_KEY # The key inside that Secret
      volumes:
        - name: tmp
          emptyDir: {}
