apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-fe-multi-ride
  namespace: multi-ride-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-multi-ride
  template:
    metadata:
      labels:
        app: app-multi-ride
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: fend-multi-ride
          image: naveensasalu/multi-ride-frontend:1.0.1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 80
          env:
            - name: GOOGLE_MAPS_API_KEY # This is the name your Node.js code looks for
              valueFrom:
                secretKeyRef:
                  name: maps-secrets # The name of the K8s Secret
                  key: GOOGLE_API_KEY # The key inside that Secret
