apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaayaka-games
  namespace: games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaayaka-games
  template:
    metadata:
      labels:
        app: kaayaka-games
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: games
          image: docker.io/naveensasalu/kaayaka-games:6305f0d16ca071c92f81b89d725bb4039036c989
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /run
      volumes:
        - name: tmp
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
