apiVersion: apps/v1
kind: Deployment
metadata:
  name: farm-backend
  namespace: multi-farm
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: naveensasalu/farm-backend:2.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            # Secrets from the 'multi-farm' namespace
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: jwt-secret-key
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: minio-root-user
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: minio-password
            # Connection to Postgres in the 'infra' namespace
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: database-url
            - name: MINIO_EXTERNAL_URL
              value: "https://mnio.kaayaka.in"
            - name: ALLOWED_ORIGINS
              value: "https://of.kaayaka.in"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: multi-farm
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
