apiVersion: batch/v1
kind: Job
metadata:
  name: init-farm-data
  namespace: multi-farm
spec:
  template:
    spec:
      containers:
        - name: init-data
          image: naveensasalu/farm-backend:1.0.2
          # This command runs both scripts in order
          command:
            [
              "/bin/sh",
              "-c",
              "python app/initial_data.py && python app/seed_db.py",
            ]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: database-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: jwt-secret-key
      restartPolicy: OnFailure
