apiVersion: batch/v1
kind: Job
metadata:
  generateName: init-farm-data-
  namespace: multi-farm
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
        - name: init-data
          image: naveensasalu/farm-backend:1.0.1
          command:
            [
              "/bin/sh",
              "-c",
              "until pg_isready -d $DATABASE_URL; do sleep 3; done && python app/initial_data.py && python app/seed_db.py",
            ]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: database-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: jwt-secret-key
      restartPolicy: OnFailure
