apiVersion: batch/v1
kind: Job
metadata:
  name: init-farm-data
  namespace: multi-farm
  annotations:
    # This tells ArgoCD to delete and recreate the Job if it changes
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  template:
    spec:
      containers:
        - name: init-data
          image: naveensasalu/farm-backend:1.0.3
          command:
            - "/bin/sh"
            - "-c"
            - |
              # Wait for DB using python
              python -c "import socket, time; 
              while True:
                  try:
                      with socket.create_connection(('postgres-service.infra.svc.cluster.local', 5432), timeout=1):
                          break
                  except:
                      time.sleep(1)"

              # Run scripts as modules
              python -m app.initial_data && python -m app.seed_db
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: farm-secrets
                  key: database-url
      restartPolicy: OnFailure
