# External Secrets Operator - connects Vault to Kubernetes Secrets
# Install ESO first:
# helm repo add external-secrets https://charts.external-secrets.io
# helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace

---
# ClusterSecretStore - cluster-wide access to Vault
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"

---
# ExternalSecret for Organic Farm
# This creates the 'farm-secrets' Secret from Vault data
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: farm-secrets
  namespace: multi-farm
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: farm-secrets  # The K8s secret name (same as before)
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret-key
      remoteRef:
        key: organic-farm/secrets
        property: jwt-secret-key
    - secretKey: database-url
      remoteRef:
        key: organic-farm/secrets
        property: database-url
    - secretKey: minio-root-user
      remoteRef:
        key: organic-farm/secrets
        property: minio-root-user
    - secretKey: minio-password
      remoteRef:
        key: organic-farm/secrets
        property: minio-password

---
# ExternalSecret for Infrastructure (PostgreSQL)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-secrets
  namespace: infra
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: infra-secrets
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: infra/secrets
        property: postgres-password

---
# ExternalSecret for Multi-Ride Maps
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maps-secrets
  namespace: multi-ride-ns
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: maps-secrets
    creationPolicy: Owner
  data:
    - secretKey: GOOGLE_API_KEY
      remoteRef:
        key: multi-ride/secrets
        property: GOOGLE_API_KEY
